services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    security_opt:
      - seccomp:unconfined
    privileged: true
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

networks:
  app_network:
    driver: bridge
