version: '3.4'
services:
  backend:
    build:
      context: .
      network: host
    image: juampi1998/visual-simd-backend:latest
    ports:
      - 8080:8080
    security_opt:
      - seccomp:unconfined
    

  frontend:
    build:
      context: .
      network: host
    image: juampi1998/visual-simd-frontend:latest
    ports:
      - 3000:3000
  
