services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    security_opt:
      - seccomp:unconfined
    privileged: true
    networks:
      - app_network    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app_network
    ports:
      - 3000:3000
  

networks:
  app_network:
    driver: bridge
